### ISSUE TITLE
Usable only on clean system

### ISSUE THREAD

**Issue by KarelWintersky** [cytopia/docker-mysql-5.7#14]
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint adoring_elbakyan (61dd70944cabdee01fa0c846bdbec98f5c8b5e36b75b64118e3e1aafc7f3b70c): Error starting userland proxy: listen tcp 127.0.0.1:3306: bind: address already in use.
```

**Comment by cytopia** [comment]
@KarelWintersky this error clearly states that MySQL cannot bind to port 3306 on `127.0.0.1` on your host system. Something else is already bound to that port.

**Comment by KarelWintersky** [comment]
I know! 
MYSQL server at host bound to 3306

**Comment by cytopia** [comment]
@KarelWintersky 
So what exactly is the issue?

**Comment by KarelWintersky** [comment]
Incorrect README, of course

**Comment by cytopia** [comment]
This project has been deprecated over the following one: https://hub.docker.com/r/devilbox/mysql
