### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/docker-entrypoint.sh\": permission denied": unknown. Error: No such container: my_tmp_mysql-5.7

### ISSUE THREAD

**Issue by PopartX** [cytopia/docker-mysql-5.7#15]
Dockerfile add

##
##
RUN chmod 777 /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

**Comment by cytopia** [comment]
This project has been deprecated over the following one: https://hub.docker.com/r/devilbox/mysql
